# Generated by Django 5.2 on 2025-04-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edirrequest',
            old_name='reviewed',
            new_name='processed',
        ),
        migrations.AddField(
            model_name='edirrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
