# Generated by Django 5.2 on 2025-05-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskgroup',
            name='shifts',
        ),
        migrations.AddField(
            model_name='task',
            name='shift',
            field=models.CharField(blank=True, choices=[('morning', 'Morning (8AM-12PM)'), ('afternoon', 'Afternoon (12PM-4PM)'), ('evening', 'Evening (4PM-8PM)'), ('night', 'Night (8PM-12AM)'), ('custom', 'Custom Shift')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='shift_custom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='shift',
            field=models.CharField(blank=True, choices=[('morning', 'Morning (8AM-12PM)'), ('afternoon', 'Afternoon (12PM-4PM)'), ('evening', 'Evening (4PM-8PM)'), ('night', 'Night (8PM-12AM)'), ('custom', 'Custom Shift')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='shift_custom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_tasks', to='tenants.member'),
        ),
    ]
