# Generated by Django 5.2 on 2025-04-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_rename_reviewed_edirrequest_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edir',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
