# Generated by Django 5.2 on 2025-04-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_edir_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='edir',
            name='unique_link',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
