# Generated by Django 5.2 on 2025-05-17 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_financialreport_payment_penalty_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='edir',
            name='account_holder_name',
            field=models.CharField(blank=True, help_text='Name as it appears on the bank account', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='edir',
            name='address',
            field=models.TextField(blank=True, help_text='Physical address of the Edir', null=True),
        ),
        migrations.AddField(
            model_name='edir',
            name='cbe_account_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='CBE account number must be 13 digits', regex='^\\d{13}$')]),
        ),
        migrations.AddField(
            model_name='edir',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current balance in ETB', max_digits=12),
        ),
        migrations.AddField(
            model_name='edir',
            name='initial_deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Initial deposit amount in ETB', max_digits=12),
        ),
        migrations.AddField(
            model_name='edirrequest',
            name='proposed_account_holder',
            field=models.CharField(blank=True, help_text='Proposed account holder name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='edirrequest',
            name='proposed_address',
            field=models.TextField(blank=True, help_text='Proposed physical address of the Edir', null=True),
        ),
        migrations.AddField(
            model_name='edirrequest',
            name='proposed_cbe_account',
            field=models.CharField(blank=True, help_text='Proposed CBE account number for the Edir', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='CBE account number must be 13 digits', regex='^\\d{13}$')]),
        ),
        migrations.AddField(
            model_name='edirrequest',
            name='proposed_initial_deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Proposed initial deposit amount in ETB', max_digits=12),
        ),
    ]
