# Generated by Django 5.2 on 2025-05-18 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_edir_account_holder_name_edir_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('all', 'All Channels')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='edir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.edir'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='recipients',
            field=models.ManyToManyField(to='tenants.member'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_type', models.CharField(choices=[('medical', 'Medical Emergency'), ('accident', 'Accident'), ('death', 'Death in Family'), ('financial', 'Financial Hardship'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('requested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='emergency_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('response_note', models.TextField(blank=True)),
                ('edir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_requests', to='tenants.edir')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_requests', to='tenants.member')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_emergencies', to='tenants.member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'General Feedback'), ('suggestion', 'Suggestion'), ('complaint', 'Complaint'), ('appreciation', 'Appreciation'), ('other', 'Other')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('edir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='tenants.edir')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='tenants.member')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_feedbacks', to='tenants.member')),
            ],
        ),
        migrations.CreateModel(
            name='Memorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_of_passing', models.DateField()),
                ('memorial_date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='memorial_photos/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_memorials', to='tenants.member')),
                ('edir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorials', to='tenants.edir')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorials', to='tenants.member')),
            ],
        ),
    ]
