# Generated by Django 5.2 on 2025-04-08 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_member_familymember_representative_spouse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='representative',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='spouse',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
