# Generated by Django 5.2 on 2025-04-08 22:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_rename_phone_member_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='date_of_designation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
