# Generated by Django 5.2 on 2025-05-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_alter_payment_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
    ]
