# Generated by Django 5.2 on 2025-05-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_remove_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='actual_attendance',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('not_recorded', 'Not Recorded')], default='not_recorded', help_text='Actual attendance recorded by coordinator', max_length=20),
        ),
    ]
