# Generated by Django 5.2 on 2025-04-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_alter_representative_date_of_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
