# Generated by Django 5.2 on 2025-05-31 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_attendance_actual_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='member_avatars/'),
        ),
    ]
