# Generated by Django 5.2 on 2025-04-08 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_alter_member_membership_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='membership_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership_id',
        ),
        migrations.RemoveField(
            model_name='spouse',
            name='membership_id',
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
