# Generated by Django 5.2 on 2025-04-08 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_remove_familymember_membership_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='registration_type',
            field=models.CharField(choices=[('single', 'Single'), ('family', 'Family')], default='single', max_length=10),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('HEAD', 'Head of Edir'), ('TREASURER', 'Treasurer (Manages finances)'), ('PROPERTY_MANAGER', 'Property Manager'), ('COORDINATOR', 'Event Coordinator'), ('MEMBER', 'Regular Member')], max_length=20)),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tenants.member')),
            ],
            options={
                'unique_together': {('member', 'role_type')},
            },
        ),
    ]
