# Generated by Django 5.2 on 2025-04-10 12:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_member_approved_at_member_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='date_assigned',
        ),
        migrations.AddField(
            model_name='role',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
