# Generated by Django 5.2 on 2025-04-10 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_remove_role_date_assigned_role_assigned_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
