# Generated by Django 5.2 on 2025-04-10 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_remove_member_is_approved_alter_member_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='member',
            name='approved_by',
        ),
    ]
