# Generated by Django 5.2 on 2025-04-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_remove_member_approved_at_remove_member_approved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='member',
            name='home_or_alternate_phone',
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('HEAD', 'Head of Edir'), ('TREASURER', 'Treasurer'), ('PROPERTY_MANAGER', 'Property Manager'), ('COORDINATOR', 'Event Coordinator'), ('MEMBER', 'Regular Member')], max_length=20),
        ),
    ]
