# Generated by Django 5.2 on 2025-04-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_remove_member_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='home_or_alternate_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
