# Generated by Django 5.2 on 2025-04-25 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_remove_member_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='home_or_alternate_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('TREASURER', 'Treasurer'), ('PROPERTY_MANAGER', 'Property Manager'), ('COORDINATOR', 'Event Coordinator'), ('MEMBER', 'Regular Member')], default='MEMBER', max_length=20),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('bereavement', 'Bereavement'), ('wedding', 'Wedding'), ('birth', 'Birth'), ('graduation', 'Graduation'), ('meeting', 'Meeting'), ('fundraising', 'Fundraising'), ('other', 'Other')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to='tenants.member')),
                ('edir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tenants.edir')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('check', 'Check'), ('other', 'Other')], max_length=50)),
                ('payment_date', models.DateField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_contributions', to='tenants.member')),
                ('edir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='tenants.edir')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='tenants.member')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='tenants.event')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spent_date', models.DateField()),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expense_receipts/')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to='tenants.member')),
                ('edir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tenants.edir')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tenants.event')),
                ('spent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tenants.member')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('attending', 'Attending'), ('not_attending', 'Not Attending'), ('maybe', 'Maybe'), ('no_response', 'No Response')], default='no_response', max_length=20)),
                ('responded_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='tenants.member')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='tenants.event')),
            ],
            options={
                'unique_together': {('event', 'member')},
            },
        ),
    ]
