# Generated by Django 5.2 on 2025-05-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0018_eventreport_taskgroup_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('TREASURER', 'Treasurer'), ('PROPERTY_MANAGER', 'Property Manager'), ('COORDINATOR', 'Event Coordinator'), ('MEMBER', 'Regular Member')], default='MEMBER', max_length=20),
        ),
    ]
