# Generated by Django 5.2 on 2025-05-08 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.event'),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.member'),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='edir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.edir'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
